enum SocketMessages {
    NEW_FOLLOW = 'NEW_FOLLOW',
    NEW_POST = 'NEW_POST',
    UPDATE_POST = 'UPDATE_POST',
    DELETE_POST = 'DELETE_POST',
    UNFOLLOW = 'UNFOLLOW',
    NEW_COMMENT = 'NEW_COMMENT',
    UPDATE_COMMENT = 'UPDATE_COMMENT',
    DELETE_COMMENT = 'DELETE_COMMENT',
    NEW_PROFILE = 'NEW_PROFILE',
    NEW_NOTIFICATION = 'NEW_NOTIFICATION'
}

export = SocketMessages